### ISSUE TITLE
Question: why the pageview tracking is commented out?

### ISSUE THREAD

**Issue by favoyang** [bykclk/vuepress-plugin-google-tag-manager#2]
Hi,

The `vuepress/plugin-google-analytics` enabled the pageview track by default.

https://github.com/vuejs/vuepress/blob/970b434ddbcb28084130d9b24c7302f7d7d94594/packages/%40vuepress/plugin-google-analytics/enhanceAppFile.js#L22:L26

But the behavior is disabled in this plugin, and why?
https://github.com/bykclk/vuepress-plugin-google-tag-manager/blob/master/inject.js#L22:L26

**Comment by bykclk** [comment]
Hi,

Sorry for the late response. I do not remember, If you think this is wrong I can fix it or you can send a pull request

**Comment by favoyang** [comment]
It was added here: https://github.com/bykclk/vuepress-plugin-google-tag-manager/commit/71b46426d28c3e4be7cbc074f2f951bf031a0421

Well, I think the plugin should track pageview by default to make it functional as described. Just uncomment should fix it. I'll leave it to you.

**Comment by bykclk** [comment]
Thank you i fixed it with the last commit, https://github.com/bykclk/vuepress-plugin-google-tag-manager/commit/843ce282e1809e04b450bf35bd405c28ea3df376
