### ISSUE TITLE
How to provide the GTM_ID to the plugin

### ISSUE THREAD

**Issue by RaimondB** [bykclk/vuepress-plugin-google-tag-manager#3]
Hi,

I want to use the plugin, but it is not clear to me how to exactly configure the GTM_ID. Where do I specify it, and what should it be named?

Kind regards,
Raimond

**Comment by bykclk** [comment]
Hi Raimond,

Sorry, I forgot to add this to the readme file. You can add it as an option.

```js
// .vuepress/config.js
module.exports = {
  plugins: [
    [
      'vuepress-plugin-google-tag-manager',
      {
        'gtm': '' // GTM-00000000
      }
    ]
  ]
}
```
